export const routes = [
  "/",
  "/about",
  "/process",
  "/services",
  "/services/custom-websites",
  "/services/seo",
  "/services/ai-visibility",
  "/pricing",
  "/work",
  "/work/analogue-room",
  "/work/standing-sun-wines",
  "/work/james-serritslev",
  "/work/bandscope",
  "/insights",
  "/insights/custom-website-vs-wordpress-for-local-businesses",
  "/insights/local-seo-for-small-shops",
  "/insights/what-is-ai-visibility-for-local-businesses",
  "/faq",
  "/contact",
  "/privacy",
] as const;
